# -*- coding: utf-8 -*-
"""final13.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLkDj5twf_3vsWFpIsp7f2hpY9Tf3_2Z
"""

print("Hello! Welcome to Age Program!")
print("I'm Sinlapachai Nantaphan M.4/4 No.13")

Year = input("\nWhat year were you born? : ")
DOB = 2026 - int(Year)
print(f"Your Age is {DOB} years old!")

import sys
!{sys.executable} -m pip install python-dateutil

from datetime import datetime
from dateutil.relativedelta import relativedelta

print("Hello! Welcome to Age Program!")
print("I'm Sinlapachai Nantaphan M.4/4 No.13")

birth_date_str = input("\nWhat is your date of birth (YYYY-MM-DD)? : ")

try:
    birth_date = datetime.strptime(birth_date_str, "%Y-%m-%d")
    today = datetime.now()

    age = relativedelta(today, birth_date)

    print(f"Your Age is {age.years} ปี {age.months} เดือน {age.days} วัน")

except ValueError:
    print("Invalid date format. Please use YYYY-MM-DD.")