# -*- coding: utf-8 -*-
"""final13.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLkDj5twf_3vsWFpIsp7f2hpY9Tf3_2Z
"""

print("Hello! Welcome to Age Program!")
print("I'm Sinlapachai Nantaphan M.4/4 No.13")

Year = input("\nWhat year were you born? : ")
DOB = 2026 - int(Year)
print(f"Your Age is {DOB} years old!")
